import { Card } from '../interfaces'

/** Dummy user data. */
export const sampleCardsData: Card[] = [
  { 
    id: 1,
    url: '/auction_1.jpg',
    days: 71,
    hours: 11,
    minutes: 10,
    secondes: 17,
    owner_name: 'Alice',
    owner_id: '@RioArham',
    owner_avatar: '/avatar_1.jpg',
    cost: '1.8BNB',
    counts: 1,
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum obcaecati dignissimos quae quo ad iste ipsum officiis deleniti asperiores sit.',
  },
  {
    id: 2,
    url: '/auction_2.jpg',
    days: 31,
    hours: 19,
    minutes: 23,
    secondes: 37,
    owner_name: 'Design Illusions',
    owner_id: '@ArtNox',
    owner_avatar: '/avatar_2.jpg',
    cost: '1.7BNB',
    counts: 3,
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum obcaecati dignissimos quae quo ad iste ipsum officiis deleniti asperiores sit.',
  },
  {
    id: 3,
    url: '/auction_3.jpg',
    days: 11,
    hours: 12,
    minutes: 56,
    secondes: 43,
    owner_name: 'Photograpy',
    owner_id: '@Junaid',
    owner_avatar: '/avatar_3.jpg',
    cost: '3.5BNB',
    counts: 2,
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum obcaecati dignissimos quae quo ad iste ipsum officiis deleniti asperiores sit.',
  },
  {
    id: 4,
    url: '/auction_4.jpg',
    days: 32,
    hours: 19,
    minutes: 23,
    secondes: 17,
    owner_name: 'Virtual Worlds',
    owner_id: '@Richard',
    owner_avatar: '/avatar_4.jpg',
    cost: '1.5BNB',
    counts: 5,
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum obcaecati dignissimos quae quo ad iste ipsum officiis deleniti asperiores sit.',
  },
]
